services:
  postgres:
    image: postgres:alpine
    container_name: faker-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: faker_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      target: development
    container_name: faker-app
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:postgrespassword@postgres:5432/faker_db?schema=public
      - PORT=3000
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
